@startuml
autonumber

actor "Gestor" as GEST
participant ":AtualizarScooterUI" as UI
participant ":AtualizarScooterController" as CONTROLLER
participant ":ScooterBD" as SCBD
participant ":BaseDados" as BD
participant "listaScooter :List<String>"
participant ":ValidarParametros" as VALID


GEST -> UI : Seleciona atualizar uma scooter
activate GEST
activate UI
UI->CONTROLLER: listaScooter=getListaScooter()
activate CONTROLLER

CONTROLLER -> SCBD : listaScooter= getListaScooter()

activate SCBD
deactivate CONTROLLER
  SCBD -> BD : connection=getConnection()
        activate BD
        deactivate BD
          SCBD -> BD : closeConnection()
        activate BD
        deactivate BD
deactivate SCBD

UI --> GEST: Apresenta a lista de scooters
deactivate UI

GEST-> UI : Seleciona o id da scooter que \n pretende atualizar
activate UI
UI->CONTROLLER: infoScooter=getScooterbyID(scooterID)
activate CONTROLLER
CONTROLLER -> SCBD : infoScooter=getScooterbyID(scooterID)

activate SCBD
deactivate CONTROLLER
 SCBD -> BD : connection=getConnection()
        activate BD
        deactivate BD
          SCBD -> BD : closeConnection()
        activate BD
        deactivate BD
deactivate SCBD
deactivate CONTROLLER
UI-->GEST: apresenta os dados da scooter\n e solicita os novos dados
deactivate UI

GEST-> UI: insere os novos dados
activate UI
UI->CONTROLLER: validaDados(carga,capacidadeBateria,\nestadoScooterID, consumoHoraBateria,\n tensao bateria,peso)
activate CONTROLLER

CONTROLLER -> VALID: validaDados(carga,capacidadeBateria,\nestadoScooterID, consumoHoraBateria,\n tensao bateria,peso)
activate VALID
deactivate VALID

deactivate CONTROLLER
UI--> GEST : apresenta os novos dados e\nsolicita confirmação
deactivate UI

GEST-> UI : confirma os dados
activate UI
UI-> CONTROLLER: updateDados(carga,capacidadeBateria,\nestadoScooterID, consumoHoraBateria,\n tensao bateria,peso)
activate CONTROLLER
CONTROLLER -> SCBD : updateDados(carga,capacidadeBateria,\nestadoScooterID, consumoHoraBateria,\n tensao bateria,peso)
activate SCBD
 SCBD -> BD : connection=getConnection()
        activate BD
        deactivate BD
          SCBD -> BD : closeConnection()
        activate BD
        deactivate BD
deactivate SCBD
deactivate CONTROLLER
deactivate UI
deactivate GEST

@enduml