@startuml
autonumber
actor "Gestor farmácia" as GER

activate GER
GER -> ":Sistema" : inicia a atualização de um drone
activate ":Sistema"
":Sistema" --> GER : apresenta a lista de drones \n e solicita que escolha um
deactivate ":Sistema"

GER -> ":Sistema" : seleciona um drone
activate ":Sistema"
":Sistema" --> GER : apresenta os dados do drone\n e solicita os novos dados
deactivate ":Sistema"

GER -> ":Sistema" : insere os novos dados
activate ":Sistema"
":Sistema" --> GER : apresenta os novos dados \n e solicita confirmação
deactivate ":Sistema"
GER->":Sistema" : confirma a atualização
activate ":Sistema"
":Sistema" --> GER : informa do sucesso da operação
deactivate ":Sistema"

deactivate GER

@enduml