@startuml
activate WatchServiceFiles
WatchServiceFiles -> EnviarEmailSegurançaTask:enviarEmail(fileName)
activate EnviarEmailSegurançaTask
EnviarEmailSegurançaTask->FileReader:pairReturn=lockFileReader(name)
activate FileReader
FileReader -> ScooterBD:scooter= getScooterByID(idScooter)
activate ScooterBD
deactivate ScooterBD

FileReader->"pair:Pair":pair=create(scooter,emailEstafeta)
activate "pair:Pair"
deactivate "pair:Pair"
FileReader->"pairReturn:Pair":pairReturn=create(localDate,pair)
activate "pairReturn:Pair"
deactivate "pairReturn:Pair"
deactivate FileReader

EnviarEmailSegurançaTask->"pairReturn:Pair":pair=getValue()
activate "pairReturn:Pair"
deactivate "pairReturn:Pair"
EnviarEmailSegurançaTask->Emails:sendEmail()
activate Emails
deactivate Emails

deactivate WatchServiceFiles
@enduml